_wandb:
    value:
        cli_version: 0.25.1
        e:
            1nvgn6qdjko38h0yj5w9bjdvvuvsg6n8:
                codePath: Model-Pipeline/scripts/evaluate_student.py
                codePathLocal: Model-Pipeline/scripts/evaluate_student.py
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "253055008768"
                        used: "59008323584"
                email: panchalhappy22@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 59054f3cbe2109c543a2257faf61da8c563e3e55
                    remote: git@github.com:abhinavdev24/FitSenseAI.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-544241ea-1482-706a-6f42-a19785eb8bb2
                host: 64151ca105f9
                memory:
                    total: "13605826560"
                os: Linux-6.6.113+-x86_64-with-glibc2.35
                program: /content/FitSenseAI/Model-Pipeline/scripts/evaluate_student.py
                python: CPython 3.12.12
                root: /content/FitSenseAI
                startedAt: "2026-03-24T03:58:01.438826Z"
                writerId: 1nvgn6qdjko38h0yj5w9bjdvvuvsg6n8
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.25.1
            "6": 5.3.0
            "12": 0.25.1
            "13": linux-x86_64
model:
    value: Qwen-2.5-7B-Student
run_id:
    value: 20260308T234052Z
