"""Centralized synthetic data fixtures for the FitSenseAI pipeline.

All constants used to generate synthetic users, profiles, workouts, and
medical data live here so they are easy to review, extend, and audit.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# User demographics
# ---------------------------------------------------------------------------

FIRST_NAMES: list[str] = [
    "Alex",
    "Jordan",
    "Taylor",
    "Riley",
    "Casey",
    "Sam",
    "Avery",
    "Drew",
    "Morgan",
    "Jamie",
    "Chris",
    "Skyler",
    "Blake",
    "Quinn",
    "Reese",
    "Peyton",
    "Logan",
    "Parker",
    "Hayden",
    "Dakota",
    "Cameron",
    "Elliot",
    "Finley",
    "Harper",
    "Indigo",
    "Jesse",
    "Kendall",
    "Lane",
    "Marlowe",
    "Nico",
    "Oakley",
    "Phoenix",
    "River",
    "Sage",
    "Spencer",
    "Tatum",
    "Emery",
    "Devon",
    "Rory",
    "Lennox",
    "Ariel",
    "Baylor",
    "Corey",
    "Darby",
    "Ellis",
    "Frankie",
    "Gray",
    "Harlow",
    "Ivy",
    "Jules",
    "Kai",
    "Luca",
    "Marley",
    "Nova",
    "Orion",
    "Piper",
    "Quincy",
    "Rowan",
    "Scout",
    "Sloane",
    "Toby",
    "Uma",
    "Val",
    "Wren",
    "Xen",
    "Yael",
    "Zara",
    "Adrian",
    "Briar",
    "Caden",
    "Dani",
    "Eden",
    "Flynn",
    "Gem",
    "Hadley",
    "Ira",
    "Jade",
    "Kit",
    "Lark",
    "Maven",
    "Nash",
    "Onyx",
    "Pax",
    "Reed",
    "Shay",
    "Tam",
    "Uri",
    "Vesper",
    "West",
    "Xander",
    "Yara",
    "Zion",
    "Arden",
    "Bay",
    "Cruz",
    "Dale",
    "Emerson",
    "Fox",
    "Glen",
    "Haven",
]

LAST_NAMES: list[str] = [
    "Shah",
    "Kim",
    "Patel",
    "Singh",
    "Brown",
    "Chen",
    "Garcia",
    "Miller",
    "Johnson",
    "Nguyen",
    "Williams",
    "Jones",
    "Davis",
    "Martinez",
    "Lopez",
    "Anderson",
    "Taylor",
    "Thomas",
    "Jackson",
    "White",
    "Harris",
    "Martin",
    "Thompson",
    "Robinson",
    "Clark",
    "Lewis",
    "Lee",
    "Walker",
    "Hall",
    "Allen",
    "Young",
    "Hernandez",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Flores",
    "Adams",
    "Nelson",
    "Hill",
    "Ramirez",
    "Campbell",
    "Mitchell",
    "Roberts",
    "Carter",
    "Phillips",
    "Evans",
    "Turner",
    "Parker",
    "Collins",
    "Edwards",
    "Stewart",
    "Sanchez",
    "Morris",
    "Rogers",
    "Reed",
    "Cook",
    "Morgan",
    "Bell",
    "Murphy",
    "Bailey",
    "Rivera",
    "Cooper",
    "Richardson",
    "Cox",
    "Howard",
    "Ward",
    "Peterson",
    "Gray",
    "Ramirez",
    "James",
    "Watson",
    "Brooks",
    "Kelly",
    "Sanders",
    "Price",
    "Bennett",
    "Wood",
    "Barnes",
    "Ross",
    "Henderson",
    "Coleman",
    "Jenkins",
    "Perry",
    "Powell",
    "Long",
    "Patterson",
    "Hughes",
    "Flores",
    "Washington",
    "Butler",
    "Simmons",
    "Foster",
    "Gonzales",
    "Bryant",
    "Alexander",
    "Russell",
    "Griffin",
    "Diaz",
    "Hayes",
]

SEX_OPTIONS: list[str] = ["male", "female", "non_binary"]

ACTIVITY_LEVELS: list[str] = ["sedentary", "light", "moderate", "active", "very_active"]

SEVERITIES: list[str] = ["mild", "moderate", "high"]

# ---------------------------------------------------------------------------
# Fitness goals
# ---------------------------------------------------------------------------

# Each entry: (goal_slug, human-readable description)
GOALS: list[tuple[str, str]] = [
    ("fat_loss", "Reduce body fat while preserving lean mass."),
    ("muscle_gain", "Increase muscle mass progressively."),
    ("strength", "Improve compound lift performance."),
    ("general_fitness", "Improve overall health and activity consistency."),
    ("endurance", "Build cardiovascular stamina for sustained effort."),
    ("flexibility", "Increase range of motion and joint mobility."),
    ("weight_maintenance", "Sustain current body weight with healthy habits."),
    ("athletic_performance", "Enhance sport-specific speed, power, and agility."),
    ("stress_reduction", "Use exercise as a tool for mental wellness."),
    ("posture_correction", "Strengthen postural muscles to reduce imbalances."),
    ("core_stability", "Develop deep core strength for injury prevention."),
    ("mobility", "Restore functional movement patterns."),
    ("balance", "Improve proprioception and stability."),
    ("hypertrophy", "Maximize muscle size through volume training."),
    ("power", "Develop explosive force output."),
    ("cardiovascular_health", "Lower resting heart rate and improve VO2 max."),
    ("metabolic_health", "Regulate blood sugar and improve insulin sensitivity."),
    ("bone_density", "Strengthen bones through weight-bearing exercise."),
    ("rehabilitation", "Recover function after injury or surgery."),
    ("active_aging", "Maintain independence and vitality with age."),
    ("sport_conditioning", "Prepare physically for a specific sport season."),
    ("race_training", "Train for a 5K, 10K, half marathon, or marathon."),
    ("triathlon_prep", "Build swim, bike, and run fitness simultaneously."),
    ("bodyweight_mastery", "Master calisthenics and relative strength skills."),
    ("functional_fitness", "Improve capacity for everyday physical tasks."),
    ("lean_bulk", "Gain muscle with minimal fat accumulation."),
    ("recomposition", "Simultaneously lose fat and gain muscle."),
    ("hormonal_balance", "Support healthy hormone levels through exercise."),
    ("sleep_improvement", "Use training to enhance sleep quality."),
    ("energy_levels", "Reduce fatigue and increase daily vitality."),
    ("longevity", "Exercise for long-term health and disease prevention."),
    ("injury_prevention", "Strengthen stabilizers to reduce injury risk."),
    ("pain_management", "Use movement therapy to reduce chronic pain."),
    ("mental_health", "Leverage exercise for anxiety and depression relief."),
    ("weight_loss_medical", "Medically supervised weight reduction program."),
    ("post_partum_recovery", "Rebuild strength and core function after childbirth."),
    ("youth_development", "Build foundational movement skills in adolescence."),
    ("senior_strength", "Prevent sarcopenia and maintain functional strength."),
    ("desk_worker_health", "Counter sedentary lifestyle with targeted movement."),
    ("overhead_strength", "Develop pressing strength for shoulder health."),
    ("grip_strength", "Improve hand and forearm strength for daily tasks."),
    ("vertical_jump", "Increase explosive lower body power."),
    ("sprint_speed", "Improve short-distance acceleration and top speed."),
    ("swimming_fitness", "Build swim-specific endurance and technique."),
    ("cycling_performance", "Improve power output and endurance on the bike."),
    ("hiking_fitness", "Build leg endurance and load-carrying capacity."),
    ("rowing_strength", "Develop posterior chain and pulling endurance."),
    ("yoga_fitness", "Combine yoga with strength and conditioning."),
    ("pilates_strength", "Integrate Pilates principles for deep stabilization."),
    ("crossfit_readiness", "Develop broad conditioning for high-intensity workouts."),
    ("powerlifting_total", "Maximize squat, bench, and deadlift competition total."),
    ("olympic_lifting", "Develop snatch and clean-and-jerk technique and strength."),
    ("strongman_prep", "Build odd-object strength and loaded carry capacity."),
    ("boxing_conditioning", "Develop hand speed, footwork, and ring endurance."),
    ("martial_arts_fitness", "Build agility and explosive power for combat sports."),
    (
        "rock_climbing_strength",
        "Develop finger, grip, and pulling strength for climbing.",
    ),
    ("surfing_fitness", "Build shoulder endurance and core stability for surfing."),
    ("skiing_conditioning", "Strengthen legs and core for ski season."),
    ("golf_fitness", "Improve rotational power and stability for golf swing."),
    (
        "tennis_conditioning",
        "Build lateral quickness and shoulder endurance for tennis.",
    ),
    (
        "basketball_fitness",
        "Develop vertical leap and anaerobic endurance for basketball.",
    ),
    (
        "soccer_conditioning",
        "Build aerobic base and multi-directional speed for soccer.",
    ),
    ("diabetes_management", "Use structured exercise to manage blood glucose levels."),
    (
        "hypertension_management",
        "Lower blood pressure through consistent aerobic activity.",
    ),
    (
        "cholesterol_improvement",
        "Reduce LDL and improve lipid profile through exercise.",
    ),
    ("immune_support", "Moderate exercise to strengthen immune function."),
    ("detox_support", "Improve lymphatic circulation and metabolic clearance."),
    ("pregnancy_fitness", "Safe prenatal exercise for strength and mobility."),
    (
        "menopause_fitness",
        "Counter hormonal changes with resistance and cardio training.",
    ),
    (
        "testosterone_optimization",
        "Use resistance training to support testosterone levels.",
    ),
    ("cortisol_reduction", "Reduce chronic stress hormone through balanced exercise."),
    ("gut_health", "Use activity to support digestive health and microbiome."),
    ("skin_health", "Improve circulation and skin tone through regular exercise."),
    ("cognitive_function", "Use aerobic exercise to enhance memory and focus."),
    ("addiction_recovery", "Use structured fitness as part of sobriety and recovery."),
    ("chronic_fatigue_management", "Gentle progressive loading for CFS/ME sufferers."),
    ("fibromyalgia_relief", "Low-impact movement to reduce fibromyalgia symptoms."),
    ("arthritis_management", "Range-of-motion and strengthening for arthritic joints."),
    ("scoliosis_management", "Targeted strengthening to support spinal curvature."),
    ("flat_feet_correction", "Strengthen foot intrinsics and ankle stabilizers."),
    ("hypermobility_stability", "Build joint stability for hypermobile individuals."),
    ("vestibular_balance", "Improve inner ear and balance system function."),
    ("pulmonary_fitness", "Build respiratory muscle strength and aerobic capacity."),
    ("cardiac_rehab", "Structured post-cardiac event exercise progression."),
    ("oncology_fitness", "Exercise support during or after cancer treatment."),
    ("auto_immune_fitness", "Low-inflammation exercise for autoimmune conditions."),
    ("thyroid_support", "Appropriate training intensity for thyroid conditions."),
    ("adrenal_fatigue_recovery", "Low-stress movement to support adrenal recovery."),
    ("pcos_management", "Insulin-sensitizing exercise for PCOS symptom relief."),
    ("endometriosis_fitness", "Low-impact training adapted for endometriosis."),
    ("ibs_fitness", "Gentle exercise to regulate digestive motility."),
    ("migraine_management", "Low-intensity movement to reduce migraine frequency."),
    ("tinnitus_wellness", "Exercise as part of tinnitus coping strategy."),
    ("vision_health", "Outdoor exercise and movement for eye health."),
    ("hearing_health", "Safe exercise without acoustic trauma for hearing."),
    ("social_fitness", "Group-based exercise for community and accountability."),
    ("habit_formation", "Build consistent exercise habits from scratch."),
    ("competitive_body_building", "Peak physique preparation for bodybuilding stage."),
]

# ---------------------------------------------------------------------------
# Medical conditions
# ---------------------------------------------------------------------------

# Each entry: (condition_slug, human-readable description)
CONDITIONS: list[tuple[str, str]] = [
    ("none", "No known chronic medical condition."),
    ("hypertension", "Elevated blood pressure requiring monitoring."),
    ("type2_diabetes", "Type 2 diabetes managed with lifestyle or medication."),
    ("asthma", "Respiratory condition with intermittent symptoms."),
    ("lower_back_pain", "Recurring lower back pain requiring exercise modifications."),
    ("knee_pain", "Chronic knee discomfort requiring movement constraints."),
    (
        "type1_diabetes",
        "Insulin-dependent diabetes requiring careful glucose monitoring.",
    ),
    ("obesity", "BMI above 30 requiring medically guided weight management."),
    ("osteoporosis", "Reduced bone density increasing fracture risk."),
    ("osteoarthritis", "Degenerative joint disease causing pain and stiffness."),
    ("rheumatoid_arthritis", "Autoimmune inflammatory joint disease."),
    ("fibromyalgia", "Widespread musculoskeletal pain with fatigue."),
    (
        "chronic_fatigue_syndrome",
        "Persistent debilitating fatigue not relieved by rest.",
    ),
    ("hypothyroidism", "Underactive thyroid causing low metabolism and fatigue."),
    ("hyperthyroidism", "Overactive thyroid causing rapid heart rate and weight loss."),
    ("copd", "Chronic obstructive pulmonary disease limiting airflow."),
    ("heart_disease", "Coronary artery disease or prior cardiac event."),
    ("heart_failure", "Reduced cardiac output requiring carefully monitored activity."),
    (
        "atrial_fibrillation",
        "Irregular heart rhythm requiring rate and activity management.",
    ),
    ("pacemaker", "Implanted cardiac device with exercise intensity limits."),
    ("stroke_history", "Prior cerebrovascular event with residual deficits."),
    ("epilepsy", "Seizure disorder requiring activity safety precautions."),
    (
        "multiple_sclerosis",
        "Demyelinating neurological disease with variable symptoms.",
    ),
    ("parkinsons", "Progressive neurological disorder affecting movement."),
    ("cerebral_palsy", "Movement disorder from early brain injury."),
    (
        "spinal_cord_injury",
        "Partial or complete spinal cord damage affecting mobility.",
    ),
    (
        "hip_replacement",
        "Total or partial hip arthroplasty with movement restrictions.",
    ),
    ("knee_replacement", "Total or partial knee arthroplasty with load restrictions."),
    (
        "rotator_cuff_tear",
        "Partial or full rotator cuff injury limiting overhead work.",
    ),
    ("acl_reconstruction", "Post-surgical ACL rehabilitation protocol."),
    ("plantar_fasciitis", "Heel and arch pain limiting weight-bearing activity."),
    ("shin_splints", "Medial tibial stress syndrome from overuse."),
    ("stress_fracture", "Bone stress injury requiring offloading."),
    ("herniated_disc", "Spinal disc protrusion causing nerve compression and pain."),
    ("sciatica", "Sciatic nerve irritation causing radiating leg pain."),
    ("scoliosis", "Lateral spinal curvature requiring targeted strengthening."),
    ("kyphosis", "Excessive thoracic spine curvature requiring postural correction."),
    ("lordosis", "Excessive lumbar curve requiring core and hip intervention."),
    ("flat_feet", "Reduced medial arch requiring foot and ankle strengthening."),
    ("hypermobility_syndrome", "Excessive joint laxity increasing injury risk."),
    ("anxiety_disorder", "Chronic anxiety affecting exercise tolerance and adherence."),
    ("depression", "Major depressive disorder where exercise is a therapeutic tool."),
    ("bipolar_disorder", "Mood disorder requiring stable training schedules."),
    ("adhd", "Attention deficit disorder benefiting from structured exercise."),
    (
        "autism_spectrum",
        "Neurodevelopmental condition requiring adapted fitness approaches.",
    ),
    (
        "eating_disorder_recovery",
        "Recovering from anorexia, bulimia, or binge eating disorder.",
    ),
    (
        "addiction_recovery",
        "Post-substance use disorder using fitness as part of recovery.",
    ),
    ("ptsd", "Post-traumatic stress disorder with trauma-informed exercise needs."),
    ("sleep_apnea", "Obstructed breathing during sleep causing daytime fatigue."),
    ("insomnia", "Chronic difficulty falling or staying asleep."),
    (
        "restless_leg_syndrome",
        "Uncomfortable leg sensations disrupting sleep and rest.",
    ),
    ("anemia", "Low red blood cell count causing fatigue and reduced endurance."),
    ("iron_deficiency", "Low iron stores reducing oxygen-carrying capacity."),
    (
        "vitamin_d_deficiency",
        "Low vitamin D affecting bone health and muscle function.",
    ),
    ("gout", "Uric acid crystal deposits causing acute joint pain."),
    ("lupus", "Systemic autoimmune disease causing joint and organ inflammation."),
    ("crohns_disease", "Inflammatory bowel disease causing GI pain and fatigue."),
    ("ulcerative_colitis", "Inflammatory colon disease affecting exercise tolerance."),
    ("ibs", "Irritable bowel syndrome triggered by stress and intense exercise."),
    ("celiac_disease", "Autoimmune gluten intolerance affecting nutrient absorption."),
    ("kidney_disease", "Reduced kidney function requiring exercise intensity limits."),
    ("liver_disease", "Hepatic condition requiring careful exercise programming."),
    ("pcos", "Polycystic ovary syndrome benefiting from insulin-sensitizing exercise."),
    (
        "endometriosis",
        "Pelvic inflammatory condition requiring low-impact adaptations.",
    ),
    (
        "menopause",
        "Hormonal transition requiring adapted strength and cardio training.",
    ),
    ("pregnancy", "Active pregnancy requiring prenatal exercise modifications."),
    (
        "post_partum",
        "Post-delivery recovery requiring progressive core rehabilitation.",
    ),
    (
        "erectile_dysfunction",
        "Vascular condition improved by aerobic and pelvic exercise.",
    ),
    (
        "benign_prostatic_hyperplasia",
        "Enlarged prostate requiring pelvic floor awareness.",
    ),
    ("cancer_remission", "Post-oncology treatment rebuilding strength and endurance."),
    (
        "lymphedema",
        "Lymphatic drainage impairment requiring compression and gentle exercise.",
    ),
    ("peripheral_neuropathy", "Nerve damage causing numbness and balance impairment."),
    (
        "raynauds_syndrome",
        "Vasospastic condition causing cold sensitivity in extremities.",
    ),
    ("psoriasis", "Chronic skin condition aggravated by excessive sweating."),
    ("eczema", "Inflammatory skin condition sensitive to sweat and friction."),
    ("migraines", "Recurrent severe headaches triggered by intense exercise."),
    ("vertigo", "Balance disturbance requiring careful movement selection."),
    ("tinnitus", "Chronic ringing in ears worsened by high-decibel environments."),
    (
        "macular_degeneration",
        "Central vision loss requiring adapted spatial awareness.",
    ),
    ("glaucoma", "Elevated eye pressure limiting inversion and breath-hold exercises."),
    (
        "hearing_impairment",
        "Partial or full hearing loss requiring visual exercise cues.",
    ),
    ("obesity_hypoventilation", "Respiratory compromise linked to severe obesity."),
    (
        "metabolic_syndrome",
        "Cluster of conditions increasing cardiovascular disease risk.",
    ),
    (
        "non_alcoholic_fatty_liver",
        "Liver fat accumulation improved by aerobic exercise.",
    ),
    (
        "insulin_resistance",
        "Impaired glucose uptake benefiting from resistance training.",
    ),
    ("hyperlipidemia", "Elevated blood lipids managed through aerobic exercise."),
    (
        "peripheral_artery_disease",
        "Reduced limb blood flow causing claudication during exercise.",
    ),
    (
        "deep_vein_thrombosis_history",
        "Prior blood clot requiring monitored return to activity.",
    ),
    (
        "pulmonary_embolism_history",
        "Prior lung clot with graduated return to exercise.",
    ),
    (
        "long_covid",
        "Persistent post-COVID symptoms including fatigue and breathlessness.",
    ),
    (
        "post_surgical_recovery",
        "General post-operative rehabilitation requiring phased loading.",
    ),
    (
        "concussion_history",
        "Prior traumatic brain injury with exertion tolerance limits.",
    ),
    (
        "overtraining_syndrome",
        "Maladaptive training response requiring deload and recovery.",
    ),
    ("relative_energy_deficiency", "RED-S from chronic underfueling in athletes."),
    (
        "exercise_induced_bronchoconstriction",
        "Airway narrowing triggered by sustained aerobic effort.",
    ),
    (
        "exercise_induced_urticaria",
        "Allergic skin reaction triggered by physical exertion.",
    ),
    (
        "hypertrophic_cardiomyopathy",
        "Thickened heart muscle requiring strict intensity limits.",
    ),
    (
        "marfan_syndrome",
        "Connective tissue disorder with cardiovascular exercise precautions.",
    ),
    (
        "ehlers_danlos_syndrome",
        "Collagen disorder causing hypermobility and fragile tissues.",
    ),
    ("down_syndrome", "Chromosomal condition with adapted fitness programming needs."),
]

# ---------------------------------------------------------------------------
# Medications
# ---------------------------------------------------------------------------

MEDICATIONS: list[str] = [
    "Metformin",
    "Lisinopril",
    "Albuterol",
    "Ibuprofen",
    "Atorvastatin",
    "Amlodipine",
    "Omeprazole",
    "Levothyroxine",
    "Losartan",
    "Simvastatin",
    "Metoprolol",
    "Aspirin",
    "Gabapentin",
    "Sertraline",
    "Fluoxetine",
    "Escitalopram",
    "Bupropion",
    "Duloxetine",
    "Venlafaxine",
    "Amitriptyline",
    "Quetiapine",
    "Aripiprazole",
    "Risperidone",
    "Clonazepam",
    "Alprazolam",
    "Lorazepam",
    "Zolpidem",
    "Melatonin",
    "Hydrochlorothiazide",
    "Furosemide",
    "Spironolactone",
    "Warfarin",
    "Apixaban",
    "Rivaroxaban",
    "Clopidogrel",
    "Atenolol",
    "Carvedilol",
    "Bisoprolol",
    "Ramipril",
    "Enalapril",
    "Valsartan",
    "Candesartan",
    "Nitroglycerin",
    "Isosorbide Mononitrate",
    "Digoxin",
    "Amiodarone",
    "Prednisone",
    "Prednisolone",
    "Methylprednisolone",
    "Dexamethasone",
    "Montelukast",
    "Fluticasone",
    "Budesonide",
    "Tiotropium",
    "Salmeterol",
    "Formoterol",
    "Ipratropium",
    "Cetirizine",
    "Loratadine",
    "Fexofenadine",
    "Diphenhydramine",
    "Ranitidine",
    "Pantoprazole",
    "Esomeprazole",
    "Lansoprazole",
    "Ondansetron",
    "Metoclopramide",
    "Loperamide",
    "Mesalamine",
    "Sulfasalazine",
    "Hydroxychloroquine",
    "Methotrexate",
    "Azathioprine",
    "Cyclosporine",
    "Mycophenolate",
    "Adalimumab",
    "Etanercept",
    "Infliximab",
    "Insulin Glargine",
    "Insulin Lispro",
    "Semaglutide",
    "Liraglutide",
    "Empagliflozin",
    "Dapagliflozin",
    "Sitagliptin",
    "Glipizide",
    "Glyburide",
    "Pioglitazone",
    "Colchicine",
    "Allopurinol",
    "Febuxostat",
    "Alendronate",
    "Risedronate",
    "Denosumab",
    "Calcium Carbonate",
    "Vitamin D3",
    "Iron Sulfate",
    "Folic Acid",
    "Cyanocobalamin",
    "Testosterone Cypionate",
    "Progesterone",
    "Estradiol",
    "Tamoxifen",
    "Letrozole",
]


MEDICATION_FREQUENCIES: list[str] = [
    "daily",
    "twice_daily",
    "as_needed",
    "at_bedtime",
    "with_meals",
    "weekly",
]

# ---------------------------------------------------------------------------
# Allergies
# ---------------------------------------------------------------------------

ALLERGENS: list[str] = [
    # Food allergens
    "peanuts",
    "tree_nuts",
    "shellfish",
    "fish",
    "milk",
    "lactose",
    "eggs",
    "wheat",
    "gluten",
    "soy",
    "sesame",
    "mustard",
    "celery",
    "lupin",
    "molluscs",
    "sulphites",
    "sunflower_seeds",
    "poppy_seeds",
    "pine_nuts",
    "almonds",
    "cashews",
    "walnuts",
    "pecans",
    "pistachios",
    "macadamia_nuts",
    "hazelnuts",
    "brazil_nuts",
    "shrimp",
    "crab",
    "lobster",
    "clams",
    "oysters",
    "scallops",
    "salmon",
    "tuna",
    "cod",
    "corn",
    "oats",
    "barley",
    "rye",
    "buckwheat",
    "kiwi",
    "banana",
    "avocado",
    "mango",
    "peach",
    "strawberry",
    "tomato",
    "garlic",
    "onion",
    "chocolate",
    "cocoa",
    "coffee",
    "alcohol",
    "red_wine",
    "beer_yeast",
    "food_dyes",
    "msg",
    "artificial_sweeteners",
    "benzoates",
    "nitrates",
    # Environmental allergens
    "pollen",
    "grass_pollen",
    "tree_pollen",
    "weed_pollen",
    "dust",
    "dust_mites",
    "mold",
    "mildew",
    "pet_dander",
    "cat_dander",
    "dog_dander",
    "cockroach",
    "rodent_dander",
    "feathers",
    "latex",
    "nickel",
    "cobalt",
    "chromium",
    "formaldehyde",
    "fragrances",
    "perfume",
    "cleaning_products",
    "chlorine",
    "sunscreen_chemicals",
    "insect_stings",
    "bee_venom",
    "wasp_venom",
    "fire_ant_venom",
    "mosquito_saliva",
    # Drug allergens
    "penicillin",
    "amoxicillin",
    "sulfa_drugs",
    "aspirin",
    "nsaids",
    "codeine",
    "morphine",
    "contrast_dye",
    "local_anesthetics",
    "tetracycline",
]

# ---------------------------------------------------------------------------
# Allergy reactions
# ---------------------------------------------------------------------------

ALLERGY_REACTIONS: list[str] = [
    # Skin reactions
    "rash",
    "hives",
    "swelling",
    "angioedema",
    "facial_swelling",
    "lip_swelling",
    "tongue_swelling",
    "eczema_flare",
    "contact_dermatitis",
    "itching",
    "redness",
    "flushing",
    "blistering",
    "peeling_skin",
    "dry_skin",
    "skin_discoloration",
    # Respiratory reactions
    "sneezing",
    "runny_nose",
    "nasal_congestion",
    "postnasal_drip",
    "coughing",
    "wheezing",
    "shortness_of_breath",
    "chest_tightness",
    "asthma_attack",
    "throat_tightening",
    "hoarse_voice",
    "sinus_pressure",
    "sinus_headache",
    # Eye reactions
    "watery_eyes",
    "red_eyes",
    "itchy_eyes",
    "eye_swelling",
    "blurred_vision",
    "light_sensitivity",
    # Gastrointestinal reactions
    "digestive_discomfort",
    "nausea",
    "vomiting",
    "diarrhea",
    "stomach_cramps",
    "bloating",
    "gas",
    "acid_reflux",
    "mouth_tingling",
    "oral_itching",
    "lip_tingling",
    "difficulty_swallowing",
    # Cardiovascular reactions
    "rapid_heart_rate",
    "low_blood_pressure",
    "dizziness",
    "lightheadedness",
    "fainting",
    "palpitations",
    "chest_pain",
    # Neurological reactions
    "headache",
    "migraine",
    "brain_fog",
    "confusion",
    "anxiety",
    "irritability",
    "insomnia",
    "fatigue",
    "weakness",
    "numbness",
    "tingling_extremities",
    # Musculoskeletal reactions
    "joint_pain",
    "muscle_aches",
    "muscle_cramps",
    "back_pain",
    # Severe systemic reactions
    "anaphylaxis",
    "anaphylactic_shock",
    "systemic_inflammation",
    "fever",
    "chills",
    "night_sweats",
    "weight_loss",
    "lymph_node_swelling",
    # Urinary reactions
    "frequent_urination",
    "urinary_urgency",
    # Reproductive reactions
    "menstrual_irregularity",
    "pelvic_pain",
    # Other
    "tinnitus",
    "ear_congestion",
    "metallic_taste",
    "loss_of_smell",
    "loss_of_taste",
    "excessive_tearing",
    "dry_mouth",
    "excessive_thirst",
]
# ---------------------------------------------------------------------------
# Exercise catalog
# ---------------------------------------------------------------------------

EQUIPMENT: list[tuple[str, str]] = [
    # Free weights
    ("barbell", "free_weights"),
    ("dumbbell", "free_weights"),
    ("kettlebell", "free_weights"),
    ("ez_curl_bar", "free_weights"),
    ("trap_bar", "free_weights"),
    ("swiss_bar", "free_weights"),
    ("axle_bar", "free_weights"),
    ("weight_plates", "free_weights"),
    ("sandbag", "free_weights"),
    ("medicine_ball", "free_weights"),
    ("slam_ball", "free_weights"),
    ("steel_mace", "free_weights"),
    ("clubbell", "free_weights"),
    # Support / racks
    ("bench", "support"),
    ("incline_bench", "support"),
    ("decline_bench", "support"),
    ("power_rack", "support"),
    ("squat_stand", "support"),
    ("dip_bars", "support"),
    ("preacher_curl_bench", "support"),
    ("glute_ham_developer", "support"),
    ("hyperextension_bench", "support"),
    ("ab_bench", "support"),
    # Bodyweight / calisthenics
    ("pullup_bar", "bodyweight"),
    ("parallel_bars", "bodyweight"),
    ("gymnastic_rings", "bodyweight"),
    ("wall_mounted_bar", "bodyweight"),
    ("push_up_handles", "bodyweight"),
    ("ab_wheel", "bodyweight"),
    ("suspension_trainer", "bodyweight"),
    # Machines
    ("cable_machine", "machine"),
    ("leg_press_machine", "machine"),
    ("leg_extension_machine", "machine"),
    ("leg_curl_machine", "machine"),
    ("seated_row_machine", "machine"),
    ("chest_press_machine", "machine"),
    ("shoulder_press_machine", "machine"),
    ("lat_pulldown_machine", "machine"),
    ("pec_deck_machine", "machine"),
    ("hack_squat_machine", "machine"),
    ("smith_machine", "machine"),
    ("hip_abduction_machine", "machine"),
    ("hip_adduction_machine", "machine"),
    ("calf_raise_machine", "machine"),
    ("seated_calf_machine", "machine"),
    ("assisted_pullup_machine", "machine"),
    ("back_extension_machine", "machine"),
    ("abdominal_crunch_machine", "machine"),
    ("rotary_torso_machine", "machine"),
    ("chest_fly_machine", "machine"),
    ("reverse_fly_machine", "machine"),
    # Cardio
    ("treadmill", "cardio"),
    ("stationary_bike", "cardio"),
    ("rowing_machine", "cardio"),
    ("elliptical", "cardio"),
    ("stair_climber", "cardio"),
    ("ski_erg", "cardio"),
    ("assault_bike", "cardio"),
    ("jump_rope", "cardio"),
    ("battle_ropes", "cardio"),
    ("sled", "cardio"),
    ("prowler", "cardio"),
    ("fan_bike", "cardio"),
    # Accessories
    ("resistance_band", "accessory"),
    ("mini_band", "accessory"),
    ("loop_band", "accessory"),
    ("foam_roller", "accessory"),
    ("lacrosse_ball", "accessory"),
    ("massage_gun", "accessory"),
    ("yoga_mat", "accessory"),
    ("yoga_block", "accessory"),
    ("yoga_strap", "accessory"),
    ("balance_board", "accessory"),
    ("bosu_ball", "accessory"),
    ("stability_ball", "accessory"),
    ("agility_ladder", "accessory"),
    ("cone_markers", "accessory"),
    ("plyo_box", "accessory"),
    ("parallette_bars", "accessory"),
    ("wrist_roller", "accessory"),
    ("grip_strengthener", "accessory"),
    ("ankle_weights", "accessory"),
    ("weight_belt", "accessory"),
    ("lifting_straps", "accessory"),
    ("knee_sleeves", "accessory"),
    ("wrist_wraps", "accessory"),
    ("lifting_chalk", "accessory"),
    # Strongman
    ("atlas_stone", "strongman"),
    ("log_bar", "strongman"),
    ("yoke", "strongman"),
    ("farmers_carry_handles", "strongman"),
    ("tire", "strongman"),
    ("sledgehammer", "strongman"),
    # Sport-specific
    ("boxing_bag", "sport"),
    ("speed_bag", "sport"),
    ("battle_rope_anchor", "sport"),
    ("pull_sled_harness", "sport"),
    ("weighted_vest", "sport"),
    ("parachute_resistance", "sport"),
]

# ---------------------------------------------------------------------------
# Exercises — (exercise_name, primary_muscle_group)
# ---------------------------------------------------------------------------

EXERCISES: list[tuple[str, str]] = [
    # Quads
    ("Barbell Back Squat", "quads"),
    ("Barbell Front Squat", "quads"),
    ("Goblet Squat", "quads"),
    ("Leg Press", "quads"),
    ("Hack Squat", "quads"),
    ("Walking Lunge", "quads"),
    ("Reverse Lunge", "quads"),
    ("Bulgarian Split Squat", "quads"),
    ("Step Up", "quads"),
    ("Leg Extension", "quads"),
    ("Sissy Squat", "quads"),
    ("Box Squat", "quads"),
    ("Zercher Squat", "quads"),
    # Hamstrings
    ("Romanian Deadlift", "hamstrings"),
    ("Stiff Leg Deadlift", "hamstrings"),
    ("Lying Leg Curl", "hamstrings"),
    ("Seated Leg Curl", "hamstrings"),
    ("Nordic Hamstring Curl", "hamstrings"),
    ("Good Morning", "hamstrings"),
    ("Single Leg Romanian Deadlift", "hamstrings"),
    ("Glute Ham Raise", "hamstrings"),
    # Glutes
    ("Hip Thrust", "glutes"),
    ("Barbell Glute Bridge", "glutes"),
    ("Cable Kickback", "glutes"),
    ("Sumo Deadlift", "glutes"),
    ("Donkey Kick", "glutes"),
    ("Clamshell", "glutes"),
    ("Lateral Band Walk", "glutes"),
    ("Single Leg Hip Thrust", "glutes"),
    ("Frog Pump", "glutes"),
    # Calves
    ("Standing Calf Raise", "calves"),
    ("Seated Calf Raise", "calves"),
    ("Donkey Calf Raise", "calves"),
    ("Single Leg Calf Raise", "calves"),
    ("Jump Rope", "calves"),
    # Posterior chain / full
    ("Deadlift", "posterior_chain"),
    ("Trap Bar Deadlift", "posterior_chain"),
    ("Rack Pull", "posterior_chain"),
    ("Snatch Grip Deadlift", "posterior_chain"),
    ("Kettlebell Swing", "posterior_chain"),
    ("Clean", "posterior_chain"),
    ("Power Clean", "posterior_chain"),
    ("Snatch", "posterior_chain"),
    # Chest
    ("Barbell Bench Press", "chest"),
    ("Dumbbell Bench Press", "chest"),
    ("Incline Barbell Bench Press", "chest"),
    ("Incline Dumbbell Bench Press", "chest"),
    ("Decline Bench Press", "chest"),
    ("Push Up", "chest"),
    ("Wide Grip Push Up", "chest"),
    ("Dumbbell Fly", "chest"),
    ("Cable Fly", "chest"),
    ("Pec Deck Fly", "chest"),
    ("Chest Dip", "chest"),
    ("Svend Press", "chest"),
    ("Landmine Press", "chest"),
    # Back
    ("Bent Over Row", "back"),
    ("Barbell Row", "back"),
    ("Dumbbell Row", "back"),
    ("Seated Cable Row", "back"),
    ("Lat Pulldown", "back"),
    ("Pull Up", "back"),
    ("Chin Up", "back"),
    ("Neutral Grip Pull Up", "back"),
    ("Chest Supported Row", "back"),
    ("Meadows Row", "back"),
    ("T-Bar Row", "back"),
    ("Single Arm Cable Row", "back"),
    ("Face Pull", "back"),
    ("Straight Arm Pulldown", "back"),
    ("Seal Row", "back"),
    ("Pendlay Row", "back"),
    # Shoulders
    ("Overhead Press", "shoulders"),
    ("Dumbbell Shoulder Press", "shoulders"),
    ("Arnold Press", "shoulders"),
    ("Lateral Raise", "shoulders"),
    ("Cable Lateral Raise", "shoulders"),
    ("Front Raise", "shoulders"),
    ("Rear Delt Fly", "shoulders"),
    ("Reverse Pec Deck", "shoulders"),
    ("Upright Row", "shoulders"),
    ("Push Press", "shoulders"),
    ("Bradford Press", "shoulders"),
    ("Lu Raise", "shoulders"),
    # Biceps
    ("Barbell Curl", "biceps"),
    ("Dumbbell Curl", "biceps"),
    ("Hammer Curl", "biceps"),
    ("Incline Dumbbell Curl", "biceps"),
    ("Concentration Curl", "biceps"),
    ("Preacher Curl", "biceps"),
    ("Cable Curl", "biceps"),
    ("EZ Bar Curl", "biceps"),
    ("Spider Curl", "biceps"),
    ("Zottman Curl", "biceps"),
    # Triceps
    ("Tricep Pushdown", "triceps"),
    ("Skull Crusher", "triceps"),
    ("Overhead Tricep Extension", "triceps"),
    ("Close Grip Bench Press", "triceps"),
    ("Tricep Dip", "triceps"),
    ("Diamond Push Up", "triceps"),
    ("Cable Overhead Tricep Extension", "triceps"),
    ("Kickback", "triceps"),
    ("JM Press", "triceps"),
    # Forearms / grip
    ("Wrist Curl", "forearms"),
    ("Reverse Wrist Curl", "forearms"),
    ("Farmers Carry", "forearms"),
    ("Dead Hang", "forearms"),
    ("Plate Pinch", "forearms"),
    ("Towel Pull Up", "forearms"),
    # Core
    ("Plank", "core"),
    ("Side Plank", "core"),
    ("Ab Wheel Rollout", "core"),
    ("Hanging Knee Raise", "core"),
    ("Hanging Leg Raise", "core"),
    ("Cable Crunch", "core"),
    ("Decline Crunch", "core"),
    ("Bicycle Crunch", "core"),
    ("Russian Twist", "core"),
    ("Dragon Flag", "core"),
    ("Hollow Body Hold", "core"),
    ("Dead Bug", "core"),
    ("Pallof Press", "core"),
    ("Landmine Rotation", "core"),
    ("Suitcase Carry", "core"),
    ("Copenhagen Plank", "core"),
    # Cardio / conditioning
    ("Treadmill Run", "cardiovascular"),
    ("Stationary Bike", "cardiovascular"),
    ("Rowing Machine", "cardiovascular"),
    ("Elliptical", "cardiovascular"),
    ("Stair Climber", "cardiovascular"),
    ("Assault Bike", "cardiovascular"),
    ("Ski Erg", "cardiovascular"),
    ("Battle Ropes", "cardiovascular"),
    ("Box Jump", "cardiovascular"),
    ("Burpee", "cardiovascular"),
    ("Sled Push", "cardiovascular"),
    ("Sled Pull", "cardiovascular"),
    ("Prowler Sprint", "cardiovascular"),
    ("Jump Squat", "cardiovascular"),
    ("Mountain Climber", "cardiovascular"),
    # Mobility / flexibility
    ("Hip Flexor Stretch", "mobility"),
    ("Pigeon Pose", "mobility"),
    ("World's Greatest Stretch", "mobility"),
    ("Cat Cow", "mobility"),
    ("Thoracic Rotation", "mobility"),
    ("Ankle Circles", "mobility"),
    ("90-90 Hip Stretch", "mobility"),
    ("Couch Stretch", "mobility"),
    ("Shoulder Dislocates", "mobility"),
    ("Jefferson Curl", "mobility"),
]

# ---------------------------------------------------------------------------
# Synthetic query prompt data
# ---------------------------------------------------------------------------

COACHING_QUESTIONS: list[str] = [
    "What's the best rep range for hypertrophy?",
    "Should I do cardio on rest days?",
    "How much protein do I need per day?",
    "Is it okay to work out on an empty stomach?",
    "How long should I rest between sets for strength?",
    "What are the signs of overtraining?",
    "Should I stretch before or after my workout?",
    "How do I break through a strength plateau?",
    "Is creatine safe to take daily?",
    "How important is sleep for muscle recovery?",
]

# (name, default_sets, default_reps, default_weight_kg)
EXERCISE_POOL: list[tuple[str, int, int, int]] = [
    ("bench press", 3, 10, 60),
    ("squats", 4, 8, 80),
    ("deadlifts", 3, 5, 100),
    ("overhead press", 3, 10, 40),
    ("barbell rows", 4, 8, 60),
    ("lunges", 3, 12, 30),
    ("pull-ups", 3, 8, 0),
    ("leg press", 4, 10, 120),
    ("dumbbell curls", 3, 12, 12),
    ("tricep dips", 3, 10, 0),
]
